// Objective-C API for talking to github.com/lestar348/xray-core-mobile-wrapper Go package.
//   gobind -lang=objc github.com/lestar348/xray-core-mobile-wrapper
//
// File is generated by gobind. Do not edit.

#ifndef __XRay_H__
#define __XRay_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class XRayCustomHandler;
@protocol XRayLogger;
@class XRayLogger;

@protocol XRayLogger <NSObject>
- (void)logInput:(NSString* _Nullable)s;
@end

@interface XRayCustomHandler : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped method CustomHandler.Handle with unsupported parameter or return types

@end

FOUNDATION_EXPORT void XRaySetMemoryLimit(void);

FOUNDATION_EXPORT BOOL XRayStartXray(NSData* _Nullable config, id<XRayLogger> _Nullable logger, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT void XRayStopXray(void);

@class XRayLogger;

@interface XRayLogger : NSObject <goSeqRefInterface, XRayLogger> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)logInput:(NSString* _Nullable)s;
@end

#endif
