
// Objective-C API for talking to the following Go packages
//
//	github.com/lestar348/xray-core-mobile-wrapper
//
// File is generated by gomobile bind. Do not edit.
#ifndef __XRayCoreIOSWrapper_FRAMEWORK_H__
#define __XRayCoreIOSWrapper_FRAMEWORK_H__

#include "XRay.objc.h"
#include "Universe.objc.h"

#endif
